api-version: 1.13

name: ${project.parent.name}
version: ${project.version}
description: '${project.parent.description}'

main: dev.imprex.testsuite.TestsuitePlugin

author: NgLoader

commands:
  testsuite:
    aliases: [test]
